/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2019-04-17 09:01:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.Database;
import java.util.*;

public final class posummary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	String temp;
	int er=0;
	String sub="dmkd";
	String year="2017";
	int sum=0,sum1=0;
	float per=0f;
	int ut1[][]=new int[250][40];
	String pos[][]=new String[250][40];
	int t=0,q=0,m=0,p=0;
	float posv[][]=new float[250][40];
	int max[]=new int[250];
	int nco=0,tar=60,req=60;
	int num=0;
	int totalcoy[]=new int[200];
	int totalcon[]=new int[200];
	int totalc[]=new int[200];
	float totalavg[]=new float[200];
	int entries=0;
	float tot[]=new float[12];
	String cos []=new String[20];
	int count=0;
	ArrayList<String> cose = new ArrayList<String>();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/HP/Desktop/apache-tomcat-9.0.10/webapps/project1/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1534663976000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Database");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("function pth()\r\n");
      out.write("{\r\n");
      out.write("\talert(document.getElementById(\"file\").files[0].path);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"canvasjs.min.js\"> </script>\r\n");
      out.write("<style>\r\n");
      out.write("tr,td{\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<center><image src=\"Logo.png\" width=1000 height=200></image></center>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

sub=request.getParameter("sub");
System.out.println("sub is:"+sub);
year=request.getParameter("year");

      out.write("\r\n");
      out.write("<h1>");
      out.print(sub );
      out.write(" Program attainment</h1>\r\n");
      out.write("<form method=\"post\" action=\"allposummary.jsp?sub=");
      out.print(sub);
      out.write("&year=");
      out.print(year);
      out.write("\">\r\n");
      out.write("<table border=\"5\" align=\"center\" width=\"70%\">\r\n");

try
{
	Connection con=Database.dataConnection();
	Statement stmt=con.createStatement();
	
	ArrayList<String> tables = new ArrayList<String>();
	
	String all="show tables";
	ResultSet rs12=stmt.executeQuery(all);
	while(rs12.next())
	{
		tables.add(rs12.getString(1));
		
	}
	
	String c5=year+"_"+sub+"_co";

	int flag5=1;
	for(int p=0;p<tables.size();p++)
	{
		if(tables.get(p).equalsIgnoreCase(c5))
		{
			flag5=0;
		}
	}
	
	int ut=1,nq=1;
	
	if(flag5==1)
	{
			response.sendRedirect("allposummary.jsp?sub="+sub+"&year="+year);
	}
	
	String str323="select * from po";
	ResultSet rs323=stmt.executeQuery(str323);
	while(rs323.next())
	{
		cose.add(rs323.getString(1));
	}
	

	String str31="select * from "+year+"_subject where name='"+sub+"' limit 1";
	ResultSet rs31=stmt.executeQuery(str31);
	while(rs31.next())
	{
		
			tar=rs31.getInt(2);
			req=rs31.getInt(3);
	}
	
	t=0;
	p=0;
	String str2="select * from "+year+"_"+sub+"_copo";
	ResultSet rs2=stmt.executeQuery(str2);
	while(rs2.next())
	{
		sum=0;
		
		for(int k=0;k<12;k++)		//check...
		{
			
			//by default value deni hain
			//sum+=(rs2.getInt(k-2)*no);
			pos[t][k]=rs2.getString(k+2);
			if(pos[t][k].equalsIgnoreCase("L"))
			{
				posv[t][k]=0.3f;
			}
			if(pos[t][k].equalsIgnoreCase("M"))
			{
				posv[t][k]=0.5f;
			}
			if(pos[t][k].equalsIgnoreCase("H"))
			{
				posv[t][k]=0.7f;
			}
			
			p++;
		}
		t++;
	}
	
	
	System.out.println("checking"+ut1[0][0]);
	System.out.println("pos"+pos[0][0]);
	System.out.println("posv"+posv[0][0]);
	
	//sub=request.getParameter("sname");
	//year=request.getParameter("year");

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("CO\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO1\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO2\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO3\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO4\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO5\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO6\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO7\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO8\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO9\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO10\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO11\r\n");
      out.write("</th>\r\n");
      out.write("<th>\r\n");
      out.write("PO12\r\n");
      out.write("</th>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");

	int i=0;
	
	String str="select * from "+year+"_"+sub+"_co";
	ResultSet rs=stmt.executeQuery(str);
	while(rs.next())
	{
		count++;
		cos[i]=rs.getString(1);
		i++;
	}
	
	String str123="select * from "+year+"_"+sub+"_comix";
	ResultSet rs123=stmt.executeQuery(str123);
	double to[]=new double[10];
	
	int j=0;
	while(rs123.next())
	{
		
		to[j]=rs123.getInt(2)+rs123.getInt(3)+rs123.getInt(4)+rs123.getInt(5);
		for(int y=0;y<12;y++)
		{
			tot[y]+=to[j]*posv[j][y];
		}
		System.out.println(to[j]);

      out.write("\t\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("co");
      out.print(j+1);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][0]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][1]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][2]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][3]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][4]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][5]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][6]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][7]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][8]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][9]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][10]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(to[j]*posv[j][11]);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("\r\n");

j++;
	}
}
catch(Exception e)
{
	System.out.println(e);
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<div style=\"height: 370px; width: 100%;\">\r\n");
      out.write("<div id=\"chartContainer\" style=\"height: 370px; width: 100%;\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var dps=[];\r\n");
      out.write("window.onload = function () {\r\n");
      out.write("\r\n");
      out.write("var chart = new CanvasJS.Chart(\"chartContainer\", {\r\n");
      out.write("\ttheme: \"light1\", // \"light2\", \"dark1\", \"dark2\"\r\n");
      out.write("\tanimationEnabled: true, // change to true\t\r\n");
      out.write("\taxisY:\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tmaximum:100,\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t\r\n");
      out.write("\ttitle:{\r\n");
      out.write("\t\ttext: \"Chart\"\r\n");
      out.write("\t},\r\n");
      out.write("\t\r\n");
      out.write("\tdata: [\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// Change type to \"bar\", \"area\", \"spline\", \"pie\",etc.\r\n");
      out.write("\t\ttype: \"column\",\r\n");
      out.write("\t\tdataPoints: dps\r\n");
      out.write("\t}\r\n");
      out.write("\t]\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("chart.render();\r\n");
      out.write("\r\n");
      out.write("var updateChart = function () {\r\n");
      out.write("\t//yVal = yVal +  Math.round(5 + Math.random() *(-5-5));\r\n");
      out.write("\t\tvar a= new Array();\r\n");
      out.write("\t\tvar b1= new Array();\r\n");
      out.write("\t\t\r\n");
      out.write("\t");

	for (int j=0; j < 12; j++) {
	
      out.write("\r\n");
      out.write("\ta[");
      out.print( j );
      out.write("] = ");
      out.print(tot[j] );
      out.write(";\r\n");
      out.write("\tb1[");
      out.print( j );
      out.write("] = \"");
      out.print(cose.get(j) );
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar newdps={label: \"po");
      out.print( j );
      out.write("\", y: a[");
      out.print( j );
      out.write("]}\r\n");
      out.write("\tdps.push(newdps);\r\n");
      out.write("\t");
}
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t//alert(arr);\r\n");
      out.write("\t\r\n");
      out.write("\tdelete this.a;\r\n");
      out.write("\r\n");
      out.write("chart.render();\r\n");
      out.write("\r\n");
      out.write("};\r\n");
      out.write("//setInterval(function(){updateChart()}, 1000); \r\n");
      out.write("updateChart();\r\n");
      out.write("\r\n");
      out.write("chart.render();\r\n");
      out.write("chart.getCredits().setEnabled(false);\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- <a href=\"allposummary.jsp?sub=");
      out.print(sub);
      out.write("&year=");
      out.print(year);
      out.write("\">submit</a> -->\r\n");
      out.write("<h3>LEGEND</h3>\r\n");
      out.write("<table  border=\"5\" align=\"center\" width=\"70%\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("PO no.\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("PO name\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

	for(int f=0;f<12;f++)
	{

      out.write("\r\n");
      out.write("<tr align=\"left\">\r\n");
      out.write("<td>\r\n");
      out.print(f);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.print(cose.get(f));
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

	}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<center><b>Department of Computer Engineering,BV(DU)COEP</b></center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
