/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2019-04-17 09:00:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.Database;
import java.util.*;

public final class prac_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	String sub="os";
	String year="2025";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Database");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("function pth()\r\n");
      out.write("{\r\n");
      out.write("\talert(document.getElementById(\"file\").files[0].path);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("tr,td{\r\n");
      out.write("text-align:center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<center><image src=\"Logo.png\" width=1000 height=200></image></center>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

sub=request.getParameter("sub");
year=request.getParameter("year");


      out.write("\r\n");
      out.write("<h1>");
      out.print(sub );
      out.write(" Practical marks</h1>\r\n");
      out.write("<form method=\"post\" action=\"addprac.jsp?sub=");
      out.print(sub);
      out.write("&year=");
      out.print(year);
      out.write("\">\r\n");
      out.write("<table border=\"5\" align=\"center\" width=\"70%\">\r\n");

try
{
	Connection con=Database.dataConnection();
	Statement stmt=con.createStatement();
	ArrayList<String> tables = new ArrayList<String>();
	sub=request.getParameter("sub");
	year=request.getParameter("year");


	String all="show tables";
	ResultSet rs12=stmt.executeQuery(all);
	while(rs12.next())
	{
		tables.add(rs12.getString(1));
		
	}
	
	String c5=year+"_"+sub+"_practical";

	int flag5=1;
	for(int p=0;p<tables.size();p++)
	{
		if(tables.get(p).equalsIgnoreCase(c5))
		{
			flag5=0;
		}
	}
	
	int ut=1,nq=1;
	
	if(flag5==1)
	{
			response.sendRedirect("calculateut.jsp?sub="+sub+"&year="+year);
	}
	int no=2;
	
	String str1="select count(*) as Number from information_schema.columns where table_name='"+year+"_"+sub+"_practical'";
	ResultSet rs1=stmt.executeQuery(str1);
	while(rs1.next())
	{
		no=rs1.getInt(1);
		
	}
	System.out.println(no);
	//sub=request.getParameter("sname");
	//year=request.getParameter("year");

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<th>\r\n");
      out.write("Prn\r\n");
      out.write("</th>\r\n");

	int i=1,j=0;
	for(int k=1;k<(no);k++)
		{
		
		

      out.write("\r\n");
      out.write("<th>\r\n");
      out.write("p");
      out.print(k);
      out.write("\r\n");
      out.write("</th>\r\n");

		}
	String str="select * from "+year+"_"+sub+"_practical";
	ResultSet rs=stmt.executeQuery(str);
	while(rs.next())
	{


      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.print( rs.getInt(1));
      out.write("\r\n");
      out.write("</td>\r\n");

		for(int k=1;k<(no);k++)
		{
			int no1=rs.getInt(k+1);
			//by default value deni hain
			
			String n=Integer.toString(no1);
			if(no1==-1||n==null)
			{
				
				

      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");

			}
			else
			{
	

      out.write("\r\n");
      out.write("<td>\r\n");
      out.print( rs.getInt(k+1));
      out.write("\r\n");
      out.write("</td>\r\n");
	
			}
		}

      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("<a href=\"editprac.jsp?&prn=");
      out.print(rs.getInt(1));
      out.write("\">edit</a>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

	}

      out.write("c\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"prn\"/>\r\n");
      out.write("</td>\r\n");
 
		for(int k=1;k<(no);k++)
		{

      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"text\" name=\"ut\"/>\r\n");
      out.write("</td>\r\n");

		}

      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("<input type=\"submit\" value=\"add\"/>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");


}
catch(Exception e)
{
	out.println(e);
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<input type=\"text\" name=\"filetoupload\">\r\n");
      out.write("</form>\r\n");
      out.write("<button><a href=\"calculateut.jsp?sub=");
      out.print(sub);
      out.write("&year=");
      out.print(year);
      out.write("\" style=\"text-decoration:none\" style=\"text-decoration:none\">move to next page</a></button>\r\n");
      out.write("<center><b>Department of Computer Engineering,BV(DU)COEP</b></center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
