/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2019-04-17 08:51:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.Database;
import java.util.*;

public final class teach_005flogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	Integer a=1;
	Integer b=1;
	String sub="sa";
	String year="sa";


String gfm1="no";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Database");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write('\r');
      out.write('\n');

try
{
 	sub=request.getParameter("sub");
	year=request.getParameter("year");
	
	ArrayList<String> tables = new ArrayList<String>();
	System.out.println(sub+year);
	System.out.println("checking");
	Connection con=Database.dataConnection();
	Statement stmt=con.createStatement();
	
	String all="show tables";
	ResultSet rs1=stmt.executeQuery(all);
	while(rs1.next())
	{
		tables.add(rs1.getString(1));
		
	}
	
String ch=year+"_"+sub+"_copo";
int flag=1;
for(int p=0;p<tables.size();p++)
{
	if(tables.get(p).equalsIgnoreCase(ch))
	{
		flag=0;
	}
}

if(flag==0)
{
	response.sendRedirect("ut.jsp?sub="+sub+"&year="+year+"");
}
	
	String str="select ut,nq from "+year+"_"+sub+"_unit limit 1";	//change
	ResultSet rs=stmt.executeQuery(str);
	while(rs.next())
	{
		a=rs.getInt(1);
		b=rs.getInt(2);
			
	}
	System.out.println(a+" "+b);
}
catch(Exception e)
{
	
}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function check()\r\n");
      out.write("{\r\n");
      out.write("\t\r\n");
      out.write("\tvar su= \"");
      out.print(sub);
      out.write("\";\r\n");
      out.write("\tvar ye= \"");
      out.print(year);
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"sub1\").value=su;\r\n");
      out.write("\tdocument.getElementById(\"year1\").value=");
      out.print(year);
      out.write(";\r\n");
      out.write("\t\r\n");
      out.write("\tvar ut=");
      out.print(a);
      out.write(";\r\n");
      out.write("\tvar nq=");
      out.print(b);
      out.write(";\r\n");
      out.write("\t\r\n");
      out.write("\tvar n1=document.getElementById(\"co\").value;\r\n");
      out.write("\tvar n2=document.getElementById(\"div1\");\r\n");
      out.write("\r\n");
      out.write("\tn2.innerHTML=\"\";\r\n");
      out.write("\tvar i=1;\r\n");
      out.write("\tfor(i=1;i<=n1;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\telement=document.createElement(\"textarea\");\r\n");
      out.write("\t\telement.setAttribute(\"name\",\"t1\");\r\n");
      out.write("\t\tn2.appendChild(element);\r\n");
      out.write("\t\t//documnet.writeln();\r\n");
      out.write("\t\telement1=document.createElement(\"br\");\r\n");
      out.write("\t\tn2.appendChild(element1);\r\n");
      out.write("\r\n");
      out.write("\t\telement2=document.createElement(\"br\");\r\n");
      out.write("\t\tn2.appendChild(element2);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("  var table = document.getElementById(\"map1\");\r\n");
      out.write("  var row = table.insertRow(0);\r\n");
      out.write("  var i=1;\r\n");
      out.write("  row.insertCell(0).innerHTML = \"&nbsp\";\r\n");
      out.write("  for(i=0;i<12;i++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar j=i+1;\r\n");
      out.write("  \tvar ii=\"po\"+j+\" &nbsp&nbsp&nbsp&nbsp&nbsp \";\r\n");
      out.write("  \trow.insertCell(i+1).innerHTML = ii;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  for(m=1;m<=n1;m++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar row1 = table.insertRow(m);\r\n");
      out.write("  \trow1.insertCell(0).innerHTML = \"co\"+m;\r\n");
      out.write("  \t\t\r\n");
      out.write("  \tfor(n=1;n<=12;n++)\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\tvar chkbox = document.createElement(\"select\");\r\n");
      out.write("  \t\tchkbox.setAttribute(\"name\",\"copo\");\r\n");
      out.write("    \tvar option1 = document.createElement(\"option\");\r\n");
      out.write("    \toption1.innerHTML = \"L\";\r\n");
      out.write("    \toption1.value = \"L\";\r\n");
      out.write("    \tchkbox.add(option1, null);\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar option2 = document.createElement(\"option\");\r\n");
      out.write("    \toption2.innerHTML = \"M\";\r\n");
      out.write("    \toption2.value = \"M\";\r\n");
      out.write("    \tchkbox.add(option2, null);\r\n");
      out.write("\r\n");
      out.write("    \tvar option3 = document.createElement(\"option\");\r\n");
      out.write("    \toption3.innerHTML = \"H\";\r\n");
      out.write("    \toption3.value = \"H\";\r\n");
      out.write("    \tchkbox.add(option3, null);\r\n");
      out.write("  \t\trow1.insertCell(n).appendChild(chkbox);\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("//naya wala\r\n");
      out.write("var table1 = document.getElementById(\"map2\");\r\n");
      out.write("  var row = table1.insertRow(0);\r\n");
      out.write("  var i=1;\r\n");
      out.write("  row.insertCell(0).innerHTML = \"&nbsp\";\r\n");
      out.write("  for(i=0;i<ut;i++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar j=i+1;\r\n");
      out.write("  \tvar ii=\" &nbsp&nbsp&nbsp&nbsp&nbsp\"+\"ut\"+j;\r\n");
      out.write("  \trow.insertCell(i+1).innerHTML = ii;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  row = table1.insertRow(1);\r\n");
      out.write("  row.insertCell(0).innerHTML = \"&nbsp\";\r\n");
      out.write("  var i2=1,j2=0;\r\n");
      out.write("  \r\n");
      out.write("  for(i=0;i<(ut*nq);i++)\r\n");
      out.write("  {\r\n");
      out.write("\t  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(j2<nq)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tj2++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tj2=1;\r\n");
      out.write("\t\t\ti2++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("  \t\r\n");
      out.write("  \tii=\"Q\"+(i2)+\"\"+(j2)+\"&nbsp&nbsp&nbsp&nbsp\";\r\n");
      out.write("  \trow.insertCell(i+1).innerHTML = ii;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  var n4=document.getElementById(\"co\").value;\r\n");
      out.write(" \tn4++;\r\n");
      out.write("  for(m=2;m<=n4;m++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar row1 = table1.insertRow(m);\r\n");
      out.write("  \trow1.insertCell(0).innerHTML = \"co\"+(m-1);\r\n");
      out.write("  \t\t\r\n");
      out.write("  \tfor(n=1;n<=(ut*nq);n++)\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\tvar chkbox = document.createElement(\"input\");\r\n");
      out.write("  \t\tchkbox.setAttribute(\"name\",\"cout\"+m+\"\"+n);\r\n");
      out.write("    \tchkbox.type=\"checkbox\";\r\n");
      out.write("  \t\trow1.insertCell(n).appendChild(chkbox);\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  //doosra wala dabba\r\n");
      out.write("  \r\n");
      out.write("  var table2 = document.getElementById(\"map3\");\r\n");
      out.write("  n5=document.getElementById(\"prac\").value;\r\n");
      out.write("  var row = table2.insertRow(0);\r\n");
      out.write("  var i=1;\r\n");
      out.write("  row.insertCell(0).innerHTML = \"&nbsp\";\r\n");
      out.write("  for(i=0;i<n5;i++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar j=i+1;\r\n");
      out.write("  \tvar ii=\"P\"+j+\"&nbsp&nbsp&nbsp&nbsp\";\r\n");
      out.write("  \trow.insertCell(i+1).innerHTML = ii;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  var n4=document.getElementById(\"co\").value;\r\n");
      out.write("\r\n");
      out.write("  for(m=1;m<=n4;m++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar row1 = table2.insertRow(m);\r\n");
      out.write("  \trow1.insertCell(0).innerHTML = \"co\"+(m);\r\n");
      out.write("  \t\t\r\n");
      out.write("  \tfor(n=1;n<=n5;n++)\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\tvar chkbox = document.createElement(\"input\");\r\n");
      out.write("  \t\tchkbox.setAttribute(\"name\",\"prac\"+m+\"\"+n);\r\n");
      out.write("    \tchkbox.type=\"checkbox\";\r\n");
      out.write("  \t\trow1.insertCell(n).appendChild(chkbox);\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("   //teesra wala dabba\r\n");
      out.write("  \r\n");
      out.write("  var table3 = document.getElementById(\"map4\");\r\n");
      out.write("  n5=document.getElementById(\"asn\").value;\r\n");
      out.write("  var row = table3.insertRow(0);\r\n");
      out.write("  var i=1;\r\n");
      out.write("  row.insertCell(0).innerHTML = \"&nbsp\";\r\n");
      out.write("  for(i=0;i<n5;i++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar j=i+1;\r\n");
      out.write("  \tvar ii=\"A\"+j+\"&nbsp&nbsp&nbsp&nbsp\";\r\n");
      out.write("  \trow.insertCell(i+1).innerHTML = ii;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  var n4=document.getElementById(\"co\").value;\r\n");
      out.write("\r\n");
      out.write("  for(m=1;m<=n4;m++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar row1 = table3.insertRow(m);\r\n");
      out.write("  \trow1.insertCell(0).innerHTML = \"co\"+(m);\r\n");
      out.write("  \t\t\r\n");
      out.write("  \tfor(n=1;n<=n5;n++)\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\tvar chkbox = document.createElement(\"input\");\r\n");
      out.write("  \t\tchkbox.setAttribute(\"name\",\"asn\"+m+\"\"+n);\r\n");
      out.write("    \tchkbox.type=\"checkbox\";\r\n");
      out.write("  \t\trow1.insertCell(n).appendChild(chkbox);\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ///*****exams\r\n");
      out.write("  var table4 = document.getElementById(\"map5\");\r\n");
      out.write("  var row = table4.insertRow(0);\r\n");
      out.write("  var i=1;\r\n");
      out.write("  row.insertCell(0).innerHTML = \"&nbsp\";\r\n");
      out.write("  for(i=0;i<6;i++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar j=i+1;\r\n");
      out.write("  \tvar ii=\"E\"+j+\"&nbsp&nbsp&nbsp&nbsp\";\r\n");
      out.write("  \trow.insertCell(i+1).innerHTML = ii;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  var n4=document.getElementById(\"co\").value;\r\n");
      out.write("\r\n");
      out.write("  for(m=1;m<=n4;m++)\r\n");
      out.write("  {\r\n");
      out.write("  \tvar row1 = table4.insertRow(m);\r\n");
      out.write("  \trow1.insertCell(0).innerHTML = \"co\"+(m);\r\n");
      out.write("  \t\t\r\n");
      out.write("  \tfor(n=1;n<=6;n++)\r\n");
      out.write("  \t{\r\n");
      out.write("  \t\tvar chkbox = document.createElement(\"input\");\r\n");
      out.write("  \t\tchkbox.setAttribute(\"name\",\"exa\"+m+\"\"+n);\r\n");
      out.write("    \tchkbox.type=\"checkbox\";\r\n");
      out.write("  \t\trow1.insertCell(n).appendChild(chkbox);\r\n");
      out.write("  \t}\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');

gfm1=request.getParameter("gfm");
out.println(gfm1);

      out.write("\r\n");
      out.write("<center><image src=\"Logo.png\" width=1000 height=200></image></center>\r\n");
      out.write("<body>\r\n");
      out.write("<form method=\"POST\" action=\"teach_jsp.jsp?gfm=");
      out.print(gfm1);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("subject name:\r\n");
      out.write("<input type=\"textbox\" placeholder=\"Enter subject name\" name=\"sub\" id=\"sub1\" disabled>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("academic year:\r\n");
      out.write("<input type=\"textbox\" placeholder=\"Enter year\" name=\"year\" id=\"year1\" disabled>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("Enter the number of Assignments:\r\n");
      out.write("<input type=\"text\" placeholder=\"Enter number\" id=\"asn\" name=\"assign\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("Enter the number of COs:\r\n");
      out.write("<input type=\"textbox\" placeholder=\"Enter number\" id=\"co\" name=\"co\">\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"div1\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("Enter the number of Continuous Assessments:\r\n");
      out.write("<input type=\"textbox\" placeholder=\"Enter number\" id=\"prac\" name=\"prac\">\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<input type=\"button\" value=\"generate mapping\" onclick=\"check()\">\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("Enter the total number of registered/attempted students:\r\n");
      out.write("<input type=\"textbox\" name=\"req\" placeholder=\"Enter number\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("What is your target percentage(%) :\r\n");
      out.write("<input type=\"textbox\" name=\"tar\" placeholder=\"Enter percentage\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("<table id=\"map1\" border=\"0\">\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<table id=\"map2\" border=\"0\">\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<table id=\"map3\" border=\"0\">\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<table id=\"map4\" border=\"0\">\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<table id=\"map5\" border=\"0\">\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<p id=\"s\"></p>\r\n");
      out.write("\r\n");
      out.write("<input type=\"submit\" value=\"submit\"/>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("<center><b>Department of Computer Engineering,BV(DU)COEP</b></center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
